pydantic/logfire

docs/extra/tweaks.css
@Kludex if you think there are still issues, please add screenshots of what you don't like with an explanation of why you don't like it.
=> Improve darkmode colors

docs/overrides/main.html
=> Change announcement on the headers

docs/extra/tweaks.css, docs/overrides/partials/source.html
https://github.com/pydantic/logfire/assets/35119617/dd64f531-a859-4190-93d6-647489967cad
=> Add login button next to source

docs/help.md, docs/overrides/main.html
https://pydantic.slack.com/archives/C05AF4A4WRM/p1714492796146509
https://pydantic.slack.com/archives/C05AF4A4WRM/p1714492989735159
=> Small docs links tweaks

logfire/_internal/scrubbing.py, tests/test_secret_scrubbing.py
https://pydanticlogfire.slack.com/archives/C06EDRBSAH3/p1714500208780959
=> Don't scrub 'author'

logfire/_internal/json_encoder.py, logfire/_internal/json_schema.py, tests/test_json_args.py
- Closes https://github.com/pydantic/logfire/issues/66
=> Check if object is SQLAlchemy before dataclass

logfire/_internal/json_schema.py, tests/test_json_args.py
For https://github.com/pydantic/logfire/issues/66
=> Handle unloaded SQLAlchemy fields in JSON schema

logfire/_internal/json_schema.py, tests/test_json_args.py
Addresses https://pydanticlogfire.slack.com/archives/C06EDRBSAH3/p1714690890772309?thread_ts=1714690879.652709&cid=C06EDRBSAH3
=> Support a dataclass type as an argument

logfire/_internal/config.py
- Closes https://github.com/pydantic/logfire/issues/125
=> Add note about creating write tokens when user is not authenticated

docs/guides/onboarding_checklist/add_metrics.md
We should improve this page... For now, this will do.
=> Add docs for `metric_gauge`

logfire/_internal/scrubbing.py, tests/otel_integrations/test_openai.py
For cases such as https://pydanticlogfire.slack.com/archives/C06EDRBSAH3/p1715347839966829?thread_ts=1715347122.095749&cid=C06EDRBSAH3
=> Don't scrub spans from OpenAI integration

docs/guides/advanced/direct_database_connections.md
I think the "Direct Database Connection" is not exactly the wording we want to sell this idea for.
=> Add psycopg example on Direct Database Connections

docs/integrations/httpx.md, logfire/__init__.py, logfire/_internal/integrations/httpx.py, logfire/_internal/main.py, tests/otel_integrations/test_httpx.py
=> Add `logfire.instrument_httpx()`

logfire/integrations/structlog.py, pyproject.toml
As reported in https://github.com/pydantic/logfire/issues/213#issuecomment-2133700592
=> Fix structlog import

logfire/_internal/main.py, logfire/_internal/utils.py, tests/test_logfire.py
I would like to extend this to more places, but this is a good start.
=> Handle internal errors

logfire/_internal/config.py, logfire/_internal/config_params.py, tests/test_logfire.py
=> ignore_no_config setting added to pyproject.toml

logfire/_internal/cli.py, tests/test_cli.py
- Replaces https://github.com/pydantic/logfire/pull/236
=> Only delete files on `logfire clean`

logfire/_internal/auto_trace/__init__.py
https://pydantic.slack.com/archives/C05AF4A4WRM/p1719265325997419
=> Prevent 'dictionary changed size during iteration' error in ``install_auto_tracing`

logfire/_internal/collect_system_info.py
The previous implementation implicitly called `dist.metadata` 4 times for each distribution, which would read and parse a file each time. So this makes `collect_package_info` nearly 4 times faster, and makes `logfire.configure()` about 2.5x faster overall.
=> Optimize `collect_package_info`

logfire/_internal/config.py, tests/test_logfire.py
=> Fix ignore no config warning message

.github/workflows/main.yml, CHANGELOG.md, logfire-api/pyproject.toml, pyproject.toml
I made a mistake on https://github.com/pydantic/logfire/actions/runs/9807998370/job/27082996905
=> Version 0.46.1

logfire/_internal/exporters/processor_wrapper.py, tests/otel_integrations/test_sqlalchemy.py
https://pydanticlogfire.slack.com/archives/C06EDRBSAH3/p1720205732316029
=> Set sqlalchemy 'connect' spans to debug level

logfire/_internal/integrations/flask.py, logfire/_internal/integrations/psycopg.py, logfire/_internal/integrations/pymongo.py, logfire/_internal/integrations/redis.py, logfire/_internal/integrations/sqlalchemy.py, logfire/_internal/integrations/starlette.py, logfire/_internal/main.py
=> Add type hints to instrument methods

logfire/_internal/cli.py, logfire/_internal/collect_system_info.py, requirements-dev.lock, requirements.lock, tests/otel_integrations/test_anthropic.py, tests/otel_integrations/test_psycopg.py, tests/test_pydantic_plugin.py
A couple of tests started failing with the newest dependencies. The behaviour change comes from importlib but this hasn't changed in the lockfiles so I'm guessing it has to do with setuptools.
=> Update dependencies, handle change in importlib

.github/workflows/main.yml, Makefile, compose.yml, pyproject.toml, requirements-dev.lock, requirements.lock, tests/otel_integrations/test_celery.py
Inspired by https://github.com/python-arq/arq/commit/3f865a623852e8da84672140647800fe5d6128c0
=> Replace docker-compose by `testcontainers`

logfire/_internal/utils.py
Based on https://pydanticlogfire.slack.com/archives/C06EDRBSAH3/p1722021087312929?thread_ts=1722017944.332959&cid=C06EDRBSAH3
=> Handle `setuptools` changing `sys.path` for importing `packaging.version`

docs/robots.txt
=> Remove robots.txt

docs/overrides/main.html
=> Remove `noindex` from docs header

CONTRIBUTING.md, docs/index.md
A more intuitive question for the intro example
=> Use `birthday`, not `age` on original example

tests/test_console_exporter.py
Workaround for https://github.com/15r10nk/inline-snapshot/issues/113, thanks @15r10nk for finding the cause!
=> Tweak tests to avoid error from `==inline-snapshot=fix`

docs/guides/web-ui/alerts.md, mkdocs.yml
=> Alerts in Beta

docs/guides/web-ui/explore.md
Pulled this [from slack](https://pydanticlogfire.slack.com/archives/C06EDRBSAH3/p1728579369364319), contributing for posterity.
=> Add information about SQL Reference

CHANGELOG.md, logfire-api/logfire_api/_internal/integrations/fastapi.pyi, logfire-api/pyproject.toml, pyproject.toml, uv.lock
=> Release v1.3.2

docs/integrations/httpx.md, docs/integrations/openai.md, docs/integrations/use-cases/web-frameworks.md
- Closes https://github.com/pydantic/logfire/issues/581
=> Document how to instrument single client on HTTPX

logfire/_internal/integrations/aiohttp_client.py, logfire/_internal/integrations/asyncpg.py, logfire/_internal/integrations/celery.py, logfire/_internal/integrations/flask.py, logfire/_internal/integrations/httpx.py, logfire/_internal/integrations/mysql.py, logfire/_internal/integrations/pymongo.py, logfire/_internal/integrations/redis.py, logfire/_internal/integrations/requests.py, logfire/_internal/integrations/sqlalchemy.py, logfire/_internal/integrations/starlette.py, tests/otel_integrations/test_aiohttp_client.py, tests/otel_integrations/test_asyncpg.py, tests/otel_integrations/test_celery.py, tests/otel_integrations/test_flask.py, tests/otel_integrations/test_httpx.py, tests/otel_integrations/test_mysql.py, tests/otel_integrations/test_pymongo.py, tests/otel_integrations/test_redis.py, tests/otel_integrations/test_requests.py, tests/otel_integrations/test_sqlalchemy.py, tests/otel_integrations/test_starlette.py
- Closes https://github.com/pydantic/logfire/issues/528
=> Let user know what they should install

CHANGELOG.md, logfire-api/pyproject.toml, pyproject.toml, uv.lock
=> Release v2.2.1

pyproject.toml
Needs https://github.com/microsoft/pyright/issues/9454
=> Add old description back

docs/guides/advanced/using-environments.md
Fix environments docs code example (indentation typo)
=> fix code block indentation

docs/guides/advanced/environments.md
Inform about potential delay with env appearing
=> environment docs tweak

.github/workflows/daily_deps_test.yml, .github/workflows/main.yml
Closes https://github.com/pydantic/logfire/issues/580
* Removes extra `pydantic` version testing from daily CI
* Adds integration for sending slack message if any tests fail
=> Daily CI - notify about failure via slack notification

tests/test_configure.py
Fixes some random failures in this file that I only got locally
=> Add some missing `wait_for_check_token_thread` calls to tests

logfire/_internal/json_schema.py, logfire/_internal/utils.py, tests/test_formatter.py, tests/test_logfire.py
Closes https://github.com/pydantic/logfire/issues/573 by doing points 1 and 3 of https://github.com/pydantic/logfire/issues/573#issuecomment-2459859923
=> Handle internal errors in `create_json_schema`, update error message for internal error

CHANGELOG.md, logfire-api/logfire_api/_internal/auto_trace/import_hook.pyi, logfire-api/logfire_api/_internal/auto_trace/rewrite_ast.pyi, logfire-api/logfire_api/_internal/main.pyi, logfire-api/logfire_api/_internal/stack_info.pyi, logfire-api/pyproject.toml, logfire/_internal/main.py, pyproject.toml, uv.lock
=> Release v2.4.0

CHANGELOG.md, logfire-api/logfire_api/_internal/metrics.pyi, logfire-api/pyproject.toml, pyproject.toml, uv.lock
=> Release v2.4.1

docs/guides/advanced/alternative-clients.md
Closes https://github.com/pydantic/logfire/pull/485
=> Add Go example

CHANGELOG.md, logfire-api/pyproject.toml, pyproject.toml, uv.lock
=> Release v2.6.1

CHANGELOG.md, logfire-api/logfire_api/_internal/config.pyi, logfire-api/pyproject.toml, pyproject.toml, uv.lock
=> Release v2.6.2

logfire/__init__.py, tests/test_metrics.py, uv.lock
Fix https://github.com/pydantic/logfire/actions/runs/12255780781/job/34189633072
=> Update deps, fix failure caused by inline-snapshot

docs/plugins/main.py, pyproject.toml, tests/otel_integrations/test_redis.py, uv.lock
Thanks @Viicos for the inspo here.
=> Remove docs workaround and upgrade `mkdocs-material`

docs/integrations/faststream.md, docs/integrations/index.md, mkdocs.yml
=> Document FastStream integration

logfire/_internal/integrations/httpx.py
Also handle internal errors, including those from the user's hooks.
=> Simplify conditions in constructing httpx hooks

logfire/_internal/config.py
Small followup to https://github.com/pydantic/logfire/pull/696
Manual test script:
```python
import logfire
def generate_items():
with logfire.DEFAULT_LOGFIRE_INSTANCE._spans_tracer.start_as_current_span("Generating items"):
for i in range(3):
yield i
items = generate_items()
for item in items:
break
```
=> Prevent logged warning when span is double-ended at interpreter shutdown

logfire-api/pyproject.toml
=> Add license to Logfire API metadata

docs/how-to-guides/suppress.md, mkdocs.yml
=> docs: add suppress section

logfire/_internal/cli.py
Related to https://github.com/pydantic/logfire/issues/235.
=> Remove rich from `logfire info`

logfire/_internal/integrations/flask.py, logfire/_internal/main.py, logfire/integrations/flask.py
- Related to https://github.com/pydantic/logfire/issues/656
=> Remove `Unpack` from `instrument_flask`

logfire/_internal/integrations/sqlite3.py, logfire/_internal/main.py
- Related to https://github.com/pydantic/logfire/issues/656
=> Remove `Unpack` from `instrument_sqilte3`

CHANGELOG.md, logfire-api/logfire_api/_internal/integrations/sqlite3.pyi, logfire-api/logfire_api/_internal/integrations/wsgi.pyi, logfire-api/logfire_api/_internal/main.pyi, logfire-api/logfire_api/integrations/wsgi.pyi, logfire-api/pyproject.toml, pyproject.toml, uv.lock
=> Release v2.11.1

logfire/_internal/integrations/httpx.py, logfire/_internal/main.py, tests/otel_integrations/test_httpx.py
Parts 1 and 5 of https://github.com/pydantic/logfire/issues/655
=> Add `capture_response_text_body` to `instrument_httpx`

logfire/_internal/cli.py, tests/test_cli.py
```
(logfire) ➜  logfire git:(alex/pretty-table) logfire projects list
Organization                         | Project              
--------------------------------------|----------------------
alexmojaki                           | demo                 
alexmojaki                           | generator-demo       
alexmojaki                           | gfh                  
alexmojaki                           | ladmin               
alexmojaki                           | newproj              
alexmojaki                           | scratches            
alexmojaki                           | test-first-steps     
alexmojaki                           | test-new             
alexmojaki                           | test-proj            
alexmojaki                           | test38 …
```
=> Refactor printing tables in CLI

.github/workflows/daily_deps_test.yml, .github/workflows/main.yml, pyproject.toml, tests/test_utils.py, uv.lock
- Closes https://github.com/pydantic/logfire/issues/471
=> Support Python 3.13

pyproject.toml
https://docs.astral.sh/ruff/rules/#flake8-future-annotations-fa
=> Add FA ruff rule

docs/plugins/build_llms_txt.py, mkdocs.yml, pyproject.toml, uv.lock
https://llmstxt.org/ - more details about the purpose of the file.
=> Generate llms.txt

logfire/_internal/config.py
Closes https://github.com/pydantic/logfire/issues/779
=> Ensure cleanup when forked process ends

docs/guides/web-ui/explore.md
@alexmojaki are there other updates to do here?
=> Remove tags column from docs of metrics table

CHANGELOG.md, logfire-api/pyproject.toml, pyproject.toml, uv.lock
=> Release v3.2.0

logfire/_internal/config.py, tests/test_configure.py, uv.lock
https://opentelemetry.io/docs/specs/semconv/resource/process/#python-runtimes
=> Add process runtime information

CHANGELOG.md, logfire-api/pyproject.toml, pyproject.toml, uv.lock
=> Release v3.4.0

logfire/_internal/cli.py
Fixes https://github.com/pydantic/logfire/issues/834
=> Prevent side effects when importing logfire

CHANGELOG.md, logfire-api/pyproject.toml, pyproject.toml, uv.lock
=> Release v3.5.1

logfire/_internal/ast_utils.py, logfire/_internal/integrations/pymongo.py, logfire/_internal/metrics.py, logfire/_internal/tracer.py, logfire/integrations/wsgi.py, pyproject.toml, tests/otel_integrations/test_aws_lambda.py, tests/otel_integrations/test_mysql.py, tests/otel_integrations/test_psycopg.py, uv.lock
Fixes https://github.com/pydantic/logfire/issues/837
=> Support OpenTelemetry 1.30.0

CHANGELOG.md, logfire-api/pyproject.toml, pyproject.toml, uv.lock
=> Release v3.5.3

logfire/_internal/config.py, logfire/_internal/exporters/logs.py, logfire/_internal/exporters/otlp.py, logfire/_internal/exporters/wrapper.py, tests/test_configure.py, tests/test_otel_logs.py
And other boilerplate.
TODO later:
- scrubbing
- tail sampling
- console logging
=> Send OTel logs to logfire

CHANGELOG.md, logfire-api/pyproject.toml, pyproject.toml, uv.lock
=> Release v3.6.1

CHANGELOG.md, logfire-api/pyproject.toml, pyproject.toml, uv.lock
=> Release v3.6.4

logfire/_internal/exporters/processor_wrapper.py, tests/otel_integrations/test_httpx.py, tests/otel_integrations/test_openai.py, tests/otel_integrations/test_requests.py
https://linear.app/pydantic/issue/PYD-1775/full-url-for-outgoing-http-requests
=> Include domain in message for outgoing requests

CHANGELOG.md, logfire-api/pyproject.toml, pyproject.toml, uv.lock
=> Release v3.7.1

tests/otel_integrations/test_openai_agents.py
So we'll know when they add new ones
=> Check we know all subclasses of OpenAI agents SpanData

.github/workflows/daily_deps_test.yml, .github/workflows/main.yml
Also switch the primary python version to test from 3.12 to 3.13, and include 3.8 in daily CI
=> Test pydantic 2.11 in CI

logfire-api/logfire_api/__init__.py, logfire/__init__.py, logfire/_internal/integrations/mcp.py, logfire/_internal/main.py, tests/otel_integrations/test_openai_agents.py, tests/test_logfire_api.py
Fixes https://github.com/pydantic/logfire/issues/947
=> Add `logfire.instrument_mcp()` method

CHANGELOG.md, logfire-api/logfire_api/__init__.pyi, logfire-api/logfire_api/_internal/exporters/quiet_metrics.pyi, logfire-api/logfire_api/_internal/formatter.pyi, logfire-api/logfire_api/_internal/integrations/mcp.pyi, logfire-api/logfire_api/_internal/integrations/openai_agents.pyi, logfire-api/logfire_api/_internal/main.pyi, logfire-api/pyproject.toml, pyproject.toml, uv.lock
=> Release v3.12.0

pyproject.toml, uv.lock
If openai-agents version<0.0.7 the tests will fail
=> openai-agents version should be greater or equal to 0.0.7

CHANGELOG.md, logfire-api/logfire_api/_internal/integrations/mcp.pyi, logfire-api/pyproject.toml, pyproject.toml, uv.lock
=> Release v3.13.0

CHANGELOG.md, logfire-api/pyproject.toml, pyproject.toml, uv.lock
=> Release v3.13.1

logfire/_internal/integrations/llm_providers/llm_provider.py, tests/otel_integrations/test_openai.py, uv.lock
Fixes https://github.com/pydantic/logfire/issues/1029
=> Handle changes in openai and anthropic

logfire/_internal/config.py, tests/test_configure.py
=> Infer staging regions from write tokens

logfire/_internal/config.py, logfire/_internal/exporters/console.py, logfire/_internal/exporters/logs.py, logfire/_internal/exporters/otlp.py, logfire/_internal/exporters/test.py, logfire/_internal/exporters/wrapper.py, logfire/_internal/integrations/llm_providers/openai.py, logfire/_internal/logs.py, logfire/_internal/scrubbing.py, logfire/_internal/utils.py, logfire/testing.py, tests/conftest.py, tests/otel_integrations/test_openai_agents.py, tests/otel_integrations/test_openai_agents_mcp.py, tests/test_configure.py, tests/test_console_exporter.py, tests/test_otel_logs.py, tests/test_secret_scrubbing.py, uv.lock
Comments removed with help from AI: https://github.com/microsoft/pyright/issues/9008#issuecomment-2830314462
=> Upgrade dependencies

logfire/_internal/exporters/console.py, tests/test_console_exporter.py
Fixes https://github.com/pydantic/logfire/issues/1063
=> Fix verbose console logging with invalid json

CHANGELOG.md, logfire-api/logfire_api/_internal/exporters/processor_wrapper.pyi, logfire-api/logfire_api/_internal/integrations/mcp.pyi, logfire-api/logfire_api/_internal/main.pyi, logfire-api/pyproject.toml, pyproject.toml, uv.lock
=> Release v3.17.0

docs/how-to-guides/sampling.md
- Enhances the custom head sampling documentation with examples for different sampling rates
- Enhanced the existing example to demonstrate `TraceIdRatioBased` usage with 1% and 50% sampling rates, including expected output that shows probabilistic sampling behavior
Fixes #1018
=> docs: add custom sampling example for different span names

logfire/_internal/integrations/llm_providers/llm_provider.py, logfire/_internal/integrations/llm_providers/openai.py, tests/otel_integrations/cassettes/test_openai/test_responses_api_nonrecording.yaml, tests/otel_integrations/test_openai.py
=> Handle NonRecordingSpans correctly in OpenAI instrumentation

docs/integrations/web-frameworks/django.md
FIxes https://github.com/pydantic/logfire/issues/965, https://github.com/pydantic/logfire/issues/620
=> Improve Django integration docs

docs/how-to-guides/alternative-clients.md
Thought these might be useful.
=> docs: add additional hints to help discover Rust & JS sdks

docs/integrations/web-frameworks/django.md, docs/integrations/web-frameworks/flask.md
Addresses https://github.com/pydantic/logfire/pull/1179#issuecomment-3000810063
=> Link to Gunicorn doc page from Django and Flask doc

docs/integrations/javascript/nextjs.md
- Simplify the env needed to export data 
- Fix admonition rendering
=> docs: fix Next.js admonition

logfire-api/logfire_api/__init__.py, logfire/__init__.py, logfire/_internal/exporters/processor_wrapper.py, logfire/_internal/integrations/google_genai.py, logfire/_internal/main.py, pyproject.toml, tests/conftest.py, tests/otel_integrations/cassettes/test_google_genai/test_instrument_google_genai.yaml, tests/otel_integrations/test_google_genai.py, tests/otel_integrations/test_openai.py, tests/test_logfire_api.py, uv.lock
For https://github.com/pydantic/logfire/issues/788
=> Add instrument_google_genai

CHANGELOG.md, logfire-api/logfire_api/__init__.pyi, logfire-api/logfire_api/_internal/auth.pyi, logfire-api/logfire_api/_internal/client.pyi, logfire-api/logfire_api/_internal/config.pyi, logfire-api/logfire_api/_internal/exporters/processor_wrapper.pyi, logfire-api/logfire_api/_internal/integrations/google_genai.pyi, logfire-api/logfire_api/_internal/main.pyi, logfire-api/logfire_api/_internal/utils.pyi, logfire-api/pyproject.toml, pyproject.toml, uv.lock
=> Release v3.22.0

CHANGELOG.md, logfire-api/logfire_api/_internal/integrations/google_genai.pyi, logfire-api/pyproject.toml, pyproject.toml, uv.lock
=> Release v3.22.1

docs/how-to-guides/query-api.md, logfire-api/logfire_api/experimental/query_client.pyi, logfire/experimental/query_client.py, tests/aaa_query_client/cassettes/test_query_client/test_info_async.yaml, tests/aaa_query_client/cassettes/test_query_client/test_info_invalid_schema_async.yaml, tests/aaa_query_client/cassettes/test_query_client/test_info_invalid_schema_sync.yaml, tests/aaa_query_client/cassettes/test_query_client/test_info_sync.yaml, tests/aaa_query_client/test_query_client.py
Fixes https://github.com/pydantic/logfire/issues/1193
=> Add info method to logfire query clients

CHANGELOG.md, logfire-api/pyproject.toml, pyproject.toml, uv.lock
=> Release v3.24.2

tests/otel_integrations/test_google_genai.py
For https://github.com/pydantic/logfire/actions/runs/16830064162/job/47675351631
=> Fix `test_instrument_google_genai` for specific versions

CHANGELOG.md, logfire-api/pyproject.toml, pyproject.toml, uv.lock
=> Release v4.3.2

CHANGELOG.md, logfire-api/pyproject.toml, pyproject.toml, uv.lock
=> Release v4.3.3

CHANGELOG.md, logfire-api/pyproject.toml, pyproject.toml, uv.lock
=> Release v4.3.5

CHANGELOG.md, logfire-api/logfire_api/_internal/cli/prompt.pyi, logfire-api/pyproject.toml, pyproject.toml, uv.lock
=> Release v4.3.6

pyproject.toml, uv.lock
https://github.com/testcontainers/testcontainers-python/issues/872
https://github.com/pydantic/logfire/actions/runs/17613238469
=> Avoid buggy testcontainers

CHANGELOG.md, logfire-api/pyproject.toml, pyproject.toml, uv.lock
=> Release v4.6.0

CHANGELOG.md, logfire-api/logfire_api/_internal/cli/auth.pyi, logfire-api/logfire_api/_internal/cli/prompt.pyi, logfire-api/logfire_api/_internal/metrics.pyi, logfire-api/pyproject.toml, pyproject.toml, uv.lock
=> Release v4.10.0
