logfire/_internal/integrations/openai.py, tests/otel_integrations/test_openai.py
Fixes https://github.com/pydantic/logfire/issues/64
=> Fix OpenAI streaming empty chunk error

logfire/_internal/cli.py
- Closes https://github.com/pydantic/logfire/issues/72
=> Recommend `opentelemetry-instrumentation-sklearn` on `scikit-learn` instead of `sklearn`

tests/test_configure.py
This test fails when you have a `.logfire` on the root directory.
I'm just changing the data dir.
=> Ignore current directory on a `logfire.configure()` from the tests

tests/otel_integrations/test_sqlalchemy.py, tests/test_json_args.py
`tests/otel_integrations/test_sqlalchemy.py` instruments SQLAlchemy, which causes spans to show up in `tests/test_json_args.py` that don't show when that test is run in isolation.
=> Uninstrument SQLAlchemy after test to not mess with other tests

logfire/_internal/integrations/openai.py, tests/otel_integrations/test_openai.py
- Closes https://github.com/pydantic/logfire/issues/62
=> Improve the OpenAI integration

logfire/_internal/main.py
Without this PR, this script:
```python
import logfire
def stream():
with logfire.span('span'):
yield 1
yield 2
s = stream()
next(s)
```
logs an error: "Already shutdown, dropping span."
This PR registers exiting the span context managers with `atexit`. This happens after the tracer provider is initialized, where OTEL registers its own shutdown (and thus the shutdown of the span processors and exporters) with atexit. Since atexit runs the callbacks in reverse order of registration, that means the spans will be closed by atexit before the exporters shut down.
=> Close spans when process shuts down before the exporter shuts down and drops them

pyproject.toml
Solves https://github.com/pydantic/logfire/issues/96#issuecomment-2095456237
Added in 4.1.0: https://typing-extensions.readthedocs.io/en/latest/#typing_extensions.assert_never
=> Increase minumum typing-extensions version

logfire/_internal/main.py
Just improve readability, and add some references to other libraries.
=> Improve references in the main docstrings

logfire/_internal/cli.py
Closes https://github.com/pydantic/logfire/issues/126
For example, instead of printing:
```
To install these packages, run:
$ pip install opentelemetry-instrumentation-sqlite3 opentelemetry-instrumentation-jinja2
opentelemetry-instrumentation-urllib opentelemetry-instrumentation-urllib3    
```
it now prints:
```
To install these packages, run:
pip install opentelemetry-instrumentation-urllib opentelemetry-instrumentation-sqlite3 opentelemetry-instrumentation-jinja2 opentelemetry-instrumentation-urllib3
```
i.e. the whole command is on one line, and there's no `$`. Now triple-clicking that line (at least in my terminals) selects the whole line for easy copy-pasting.
=> Make pip install command printed by 'logfire inspect' easy to copy

logfire/_internal/integrations/fastapi.py, tests/otel_integrations/test_fastapi.py
- Closes https://github.com/pydantic/logfire/issues/74
=> Improve error when `opentelemetry-instrumentation-fastapi` is missing

logfire/__init__.py, logfire/_internal/main.py, logfire/_internal/metrics.py, tests/test_metrics.py
- Closes https://github.com/pydantic/logfire/issues/145
=> Add `logfire.metric_gauge()`

logfire/_internal/json_encoder.py, logfire/_internal/json_schema.py
Closes https://github.com/pydantic/logfire/issues/147
Tested manually by install pydantic v1 and running:
```python
import pydantic
class Foo(pydantic.BaseModel):
bar: int
baz: str
import logfire
logfire.configure(console=logfire.ConsoleOptions(verbose=True))
logfire.info('hi', foo=Foo(bar=1, baz='a'))
```
Automatic testing will require actually installing pydantic v1 in CI which is challenging. The tests fail to start in various ways with v1 installed. Using `pydantic.v1` with v2 installed doesn't reproduce the original problem.
=> Fix JSON encoding/schema of pydantic v1 models

docs/plugins/main.py
- Closes https://github.com/pydantic/logfire/issues/165
=> Use `logfire[extra]` instead of `logfire -E extra` on Poetry instructions

logfire/_internal/exporters/console.py, tests/test_console_exporter.py
- Closes https://github.com/pydantic/logfire/issues/150
=> Add exception on console

logfire/_internal/cli.py, logfire/_internal/config.py, tests/test_cli.py
- Closes https://github.com/pydantic/logfire/issues/175
=> Do not require project name on `logfire projects use` command

logfire/_internal/main.py
- Closes https://github.com/pydantic/logfire/issues/182
=> Don't use `include_url` with Pydantic's V1 `ValidationError`

docs/plugins/main.py
The psycopg was wrong, because there's a `psycopg` and a `psycopg2` installation instruction.
=> Enable multiple install instructions per page

logfire/__init__.py, logfire/_internal/main.py, logfire/integrations/loguru.py, logfire/integrations/structlog.py, tests/test_loguru.py, tests/test_stdlib_logging.py, tests/test_structlog.py
Closes https://github.com/pydantic/logfire/issues/176
Hopefully also fixes this report: https://pydanticlogfire.slack.com/archives/C06EDRBSAH3/p1715782009949009
=> Fix logging integrations with non-string messages

docs/integrations/anthropic.md, docs/integrations/openai.md, logfire/_internal/integrations/llm_providers/anthropic.py, logfire/_internal/integrations/llm_providers/llm_provider.py, logfire/_internal/integrations/llm_providers/openai.py, logfire/_internal/main.py, tests/otel_integrations/test_anthropic.py, tests/otel_integrations/test_openai.py
For a user who wanted to just `logfire.instrument_openai()` without passing a client, since they want to instrument langchain which doesn't expose/accept an openai client object: https://pydanticlogfire.slack.com/archives/C06EDRBSAH3/p1715977569378699
=> Allow instrumenting OpenAI/Anthropic client classes or modules

docs/integrations/requests.md, logfire/__init__.py, logfire/_internal/integrations/requests.py, logfire/_internal/main.py, tests/otel_integrations/test_requests.py
=> Add logfire.instrument_requests()

docs/integrations/django.md, logfire/__init__.py, logfire/_internal/integrations/django.py, logfire/_internal/main.py, tests/otel_integrations/django_test_project/django_test_site/settings.py
Hi All,
I attended the Pydantic development sprint at PyCon US, and I worked with Alex to add a Django-specific wrapper (logfire.instrument_django) to replace the client-direct call to the OpenTelemetry API.  Note, I did not complete the django.md update.
Thanks,
Roger Hurwitz
=> Add `logfire.instrument_django()`

pyproject.toml
So that the three new `instrument_*` methods now mentioned in the docs are actually available for use.
=> Uprev to version 0.35.0

docs/guides/advanced/sampling.md, docs/guides/first_steps/index.md, docs/guides/onboarding_checklist/add_auto_tracing.md, docs/guides/onboarding_checklist/integrate.md, docs/index.md, docs/integrations/anthropic.md, docs/integrations/fastapi.md, docs/integrations/logging.md, docs/integrations/openai.md, docs/integrations/psycopg.md, docs/integrations/structlog.md, logfire/__init__.py, logfire/_internal/main.py, logfire/integrations/logging.py
Step 1 of https://github.com/pydantic/logfire/issues/194
=> Use `logfire.configure()` consistently in docs

docs/integrations/fastapi.md, logfire/_internal/integrations/fastapi.py, logfire/_internal/main.py
Similar to https://github.com/pydantic/logfire/issues/193: `instrument_fastapi` exists but it didn't accept all the arguments of OTEL and encouraged using OTEL directly if those arguments were needed. This changes that, along with some other small doc updates.
=> Allow passing OTEL kwargs through instrument_fastapi

logfire/_internal/config.py, logfire/_internal/exporters/otlp.py, tests/exporters/test_otlp_session.py
After some investigation, I've found that neither OTEL nor `requests` does any retrying by default when there's a connection or timeout error while making a request.
OTEL does retry on certain status codes in a way that looks sensible so I'm leaving that case as is, although it's not the kind of problem we usually see.
It's possible to configure retries with `requests` but OTEL doesn't do so and it didn't seem easier than just coding the retries myself.
=> Retry connection errors

docs/reference/configuration.md
For https://github.com/pydantic/logfire/issues/194
=> Fix docs saying you don't need logfire.configure when using env vars

docs/guides/onboarding_checklist/add_manual_tracing.md
In particular the docs were misleading about the default arguments of `@instrument`.
=> Fix `@instrument` docs in manual tracing guide

logfire/_internal/integrations/django.py, tests/otel_integrations/test_django.py
I was looking through the logfire integrations with frameworks and libraries and found that a `ModuleNotFoundError` was not being raised in the django integration so I have added it here.
=> Improve error raised when opentelemetry.instrumentation.django is not installed

logfire/_internal/cli.py
`logfire backfill` would just print a 400 from cloudflare which was apparently unhappy about the `Content-Length` header (I don't know why). It was also missing `Authorization`.
We should test and maybe refactor this, I just wanted to make sure the command is working.
=> Fix backfill command

logfire/_internal/config.py, pyproject.toml, requirements-dev.lock
https://pydantic.slack.com/archives/C05AF4A4WRM/p1718135501452089
`import git` is quite slow so this could improve startup time a bit in some cases. Even if somehow gitpython does this job better than using subprocess, this won't matter when `.git` isn't present, which it shouldn't be in production environments.
=> Avoid importing gitpython

logfire/_internal/auto_trace/__init__.py, logfire/_internal/main.py, tests/test_auto_trace.py
Currently by default:
- Modules under the root of the current module are traced if no modules are specified
- An error is raised if modules to be traced have already been imported
This means that providing no arguments will always raise an error about wanting to trace the current module which has obviously already been imported. Either `modules` or `check_imported_modules` must be specified. This is a bit weird.
This PR makes things less weird by requiring the user to specify `modules`. This seems like a case where explicit really is better than implicit.
=> [PYD-617] Remove default for modules parameter of `install_auto_tracing`

logfire/_internal/exporters/processor_wrapper.py, tests/otel_integrations/test_fastapi.py
Fixes a small bug noticed in https://github.com/pydantic/logfire/pull/259#issuecomment-2180710771 (thanks @sneakyPad!) which happened when `http.route` and `http.target` were equal. The check for `message != name` is only for optimization and shouldn't have prevented the message from having the query params.
=> Fix query params not being in message

logfire/_internal/exporters/processor_wrapper.py, tests/otel_integrations/test_django.py, tests/otel_integrations/test_fastapi.py, tests/otel_integrations/test_starlette.py, tests/test_logfire.py
- If `otel_status_code` is `ERROR` and the log level is unset, then the log level is set to error. This way a query for `level >= level_num('error')` will generally find all kinds of errors.
- Similarly, if the log level is >= error and `otel_status_code` is `UNSET`, then `otel_status_code` is set to `ERROR`. This means that `otel_status_code = 'ERROR'` will find all errors in the same way. I think I've seen some users querying `otel_status_code` so this will make that easy and discoverable, whereas querying `level` is not super user-friendly.
=> Default the log level to error if the status code is error, and vice versa

logfire/_internal/exporters/otlp.py
So that instrumenting `requests` doesn't create spans like `POST /v1/traces`.
Tested manually by running the following script with and without these changes and without WiFi:
```python
import time
import logfire
logfire.instrument_requests()
logfire.info('hi')
logfire.force_flush()
time.sleep(100)
```
=> `suppress_instrumentation` when retrying exports

logfire/_internal/async_.py, tests/test_slow_async_callbacks.py
First part of https://linear.app/pydantic/issue/PYD-588/more-information-when-logging-slow-async-callbacks
Should help with https://pydanticlogfire.slack.com/archives/C06EDRBSAH3/p1719393315909219?thread_ts=1719218705.208939&cid=C06EDRBSAH3
=> Log async stack in `log_slow_async_callbacks`

logfire/_internal/json_encoder.py, logfire/_internal/main.py, pyproject.toml, requirements-dev.lock, requirements.lock, tests/test_json_args.py
Fixes https://github.com/pydantic/logfire/issues/276
Also upgraded lockfile versions while I was at it.
=> Fix and test unmapped SQLModels

logfire/_internal/integrations/fastapi.py, tests/otel_integrations/test_fastapi.py
Closes https://github.com/pydantic/logfire/issues/288
cc @sneakyPad
=> Ensure StaticFiles doesn't break instrument_fastapi

.github/workflows/main.yml
@alexmojaki I'll recreate the tag with this commit, and run the pipeline. I don't want to release multiple versions all the time...
=> Add verbosity to logfire-api release

logfire/_internal/db_statement_summary.py, logfire/_internal/exporters/processor_wrapper.py, tests/otel_integrations/test_sqlalchemy.py, tests/test_db_statement_summary.py
Mostly copying code from the backend.
Fixes https://linear.app/pydantic/issue/PYD-860/summarize-sql-in-more-cases. In particular having `db.name` in the span name is now accounted for so that spans from the sqlalchemy instrumentation get summaries.
=> Summarize db.statement in message

logfire/_internal/integrations/llm_providers/anthropic.py, logfire/_internal/integrations/llm_providers/llm_provider.py, logfire/_internal/integrations/llm_providers/openai.py, pyproject.toml, requirements-dev.lock, requirements.lock, tests/otel_integrations/test_anthropic.py, tests/otel_integrations/test_openai.py
Building on https://github.com/pydantic/logfire/pull/309
User request: https://pydanticlogfire.slack.com/archives/C06EDRBSAH3/p1720726405203889
Basically when an OpenAI/Anthropic client request is made to a URL that we don't specifically handle, make a generic span with the URL (which should still be somewhat useful) instead of a noisy warning log.
=> Handle and test other OpenAI/Anthropic  client methods

logfire/_internal/config.py, logfire/_internal/formatter.py, logfire/_internal/scrubbing.py, tests/test_formatter.py, tests/test_logfire.py
Addresses https://pydanticlogfire.slack.com/archives/C06EDRBSAH3/p1721433723530879
There were several places where we explicitly or implicitly raised errors which could lead to similar complaints from users. Many of these errors could be caused in the same way: by passing a preformatted string which gets unintentionally interpreted as a formatting template. I've converted all these known cases to warnings.
Previously we would warn about missing fields but continue trying to format the string. This had the small benefit of formatting other fields that weren't present, so the user gets something partially formatted. This helped in the specific case where they know what they're doing but made a typo. Keeping this behaviour would mean that something like `logfire.info("log {'1': {'2': {'3': …
=> Handle message formatting errors

logfire/integrations/loguru.py
So that this:
```python
from loguru import logger
import logfire
logger.add(**logfire.loguru_handler())
logger.info(None)
```
doesn't emit `RuntimeWarning: Failed to extract info from loguru logger`
=> Handle logging None with loguru

logfire/_internal/exporters/processor_wrapper.py, logfire/_internal/main.py, logfire/_internal/metrics.py, logfire/_internal/tracer.py, requirements-dev.lock, requirements.lock, tests/test_metrics.py
Handles new releases:
- https://github.com/open-telemetry/opentelemetry-python/releases/tag/v1.26.0
- https://github.com/open-telemetry/opentelemetry-python-contrib/releases/tag/v0.47b0
=> Update dependencies, especially OTEL

docs/integrations/index.md, docs/integrations/mysql.md, logfire-api/logfire_api/__init__.py, logfire-api/logfire_api/__init__.pyi, logfire-api/logfire_api/_internal/integrations/mysql.pyi, logfire-api/logfire_api/_internal/main.pyi, logfire/__init__.py, logfire/_internal/integrations/mysql.py, logfire/_internal/main.py, mkdocs.yml, pyproject.toml, requirements-dev.lock, requirements.lock, tests/otel_integrations/test_mysql.py
=> Add the `logfire.instrument_mysql()`

logfire/_internal/tracer.py, pyproject.toml, requirements-dev.lock, requirements.lock
Since we skip test_mysql in Python 3.8, we don't need these extra dependencies that were only for the combination of `testcontainers`, mysql, and 3.8.
Also updated the requirements locks while I'm at it.
=> Remove extra deps that were only for tests now skipped in 3.8

docs/integrations/asyncpg.md, docs/integrations/mysql.md, docs/integrations/psycopg.md
We should focus on Logfire, not on the docker here. I want to minimize not needed content on the page.
=> Hide `docker run` details on docs

CHANGELOG.md, logfire-api/logfire_api/_internal/config.pyi, logfire-api/pyproject.toml, logfire/_internal/config.py, logfire/_internal/exporters/test.py, logfire/testing.py, pyproject.toml, tests/otel_integrations/test_redis.py
Closes https://github.com/pydantic/logfire/issues/367
=> Move TestExporter to avoid requiring pytest

.github/workflows/main.yml, Makefile, pyproject.toml
`griffe` has been updated and its modules restructured. We need to update our private `mkdocstrings` wheel to use this. In the meantime, pinning griffe ensures that docs can build in CI.
=> Pin griffe to fix import errors with mkdocstrings

logfire/_internal/config.py, tests/test_collect_package_resources.py
=> Stop collecting package versions

logfire-api/logfire_api/_internal/config.pyi, logfire/_internal/config.py
This caused a failure here: https://github.com/pydantic/platform/actions/runs/10559855499/job/29252233102?pr=4053
=> Add missing `service_version` field to `_LogfireConfigData` so that it gets copied into subprocesses

logfire-api/logfire_api/_internal/config.pyi, logfire/_internal/config.py, tests/test_configure.py
`default_span_processor` is a weird parameter that mostly just adds bloat to the API docs and it makes it harder to reason about how the SDK behaves for users and make changes in the future. There's some desire to replace the `BatchSpanProcessor` and other layers with our own processor that handles batching etc. more intelligently (https://github.com/pydantic/logfire/pull/263#discussion_r1649043770, https://github.com/pydantic/logfire/pull/252#pullrequestreview-2105278545) and more specifically we've talked about dynamically tweaking the batching delay based on things like the sizes of previous batches.
The parameter isn't doing much harm right now, but we want to release a stable v1 of the SDK soon, so best to make this breaking change now. We could maybe add a deprecation warning, but …
=> PYD-1066: Remove `default_span_processor` parameter from `configure`

logfire/_internal/integrations/fastapi.py, pyproject.toml, requirements-dev.lock, requirements.lock
FastAPI released an update that broke our monkeypatching because `solve_dependencies` started returning a dataclass called `SolvedDependencies` instead of a tuple. This should make the code work with both versions.
=> Handle FastAPI update with SolvedDependencies

logfire/_internal/async_.py, logfire/_internal/auto_trace/__init__.py, logfire/_internal/auto_trace/rewrite_ast.py, logfire/_internal/integrations/fastapi.py, logfire/integrations/pydantic.py, tests/otel_integrations/test_fastapi.py, tests/test_auto_trace.py, tests/test_slow_async_callbacks.py
The OTEL instrumentation scope is a useful concept and we should use it consistently when it's appropriate. This way queries like `GROUP BY otel_scope_name` will work better for breaking down where spans are coming from.
=> Use OTEL scopes better, especially instead of tags

docs/plugins/main.py
Adds installation commands for the [uv](https://docs.astral.sh/uv/) package manager.
=> Add uv installation instructions to docs

logfire/_internal/exporters/processor_wrapper.py, tests/otel_integrations/test_fastapi.py, tests/otel_integrations/test_starlette.py
A user pointed out the websocket spans still had the route in the message, e.g. `HTTP /ws/path/{param_name}` instead of `HTTP /ws/path/param_value`.
=> Fix websocket span messages

logfire/_internal/config.py, logfire/_internal/config_params.py, logfire/_internal/scrubbing.py, tests/test_cli.py, tests/test_configure.py, tests/test_logfire.py, tests/test_secret_scrubbing.py
Deprecated kwargs are now moved into `**kwargs: DeprecatedKwargs` and undocumented to leave the remaining docs cleaner.
Internal discussion: https://pydantic.slack.com/archives/C05AF4A4WRM/p1725302678666539
=> Deprecate `project_name` in `logfire.configure()`, remove old kwargs from signature 

logfire/_internal/config.py, logfire/_internal/config_params.py, tests/test_configure.py
Internal discussion: https://pydantic.slack.com/archives/C05AF4A4WRM/p1725302678666539
=> Remove `show_summary` and `fast_shutdown` from `logfire.configure()`

logfire/_internal/config.py, logfire/_internal/utils.py, logfire/testing.py
Fixes https://github.com/pydantic/logfire/issues/437. It was closed already, but the request was reasonable, and I recently saw very different spans having the same trace and span ID in user data which was concerning. My best guess is that this was caused by a call to `random.seed`, so this should prevent that.
=> Use `SeededRandomIdGenerator` by default to prevent interference from `random.seed`

logfire-api/logfire_api/__init__.pyi, logfire/__init__.py, logfire/_internal/config.py, tests/test_logfire_api.py
Users shouldn't generally use `METRICS_PREFERRED_TEMPORALITY`, it's only for exporting to the logfire backend. I previously removed the recommendation to use it, this is finishing that off. Other backends may or may not work best with this aggregation temporality, that's up to the user doing that kind of advanced configuration.
=> Keep `METRICS_PREFERRED_TEMPORALITY` private

docs/guides/advanced/query-api.md
Address Samuel's feedback on #405.
I'll note that I am fairly confident the `Accept` header is not required, but the default value sent by requests and various other tools is or contains `*/*`; I have a PR open on the platform in order to send JSON when the Accept header contains this.
=> Update Querying API docs based on additional feedback on #405

logfire/_internal/config.py
Reported in https://pydanticlogfire.slack.com/archives/C06EDRBSAH3/p1727811173922749
Configuring with `metrics=False` still left `PeriodicExportingMetricReader`s hanging around and trying to regularly collect without being attached to a meter provider, leading to logging a warning. This prevents creating them in the first place.
=> Fix warning about unregistered MetricReaders

logfire/_internal/config.py
I'm not sure what query to make to check that the `Content-Encoding` header in included on the backend. I'm missing something... But the user is able to see their data on Logfire with this.
=> Use `Compression.Gzip`

.vscode/settings.json, CONTRIBUTING.md, logfire-api/logfire_api/_internal/config.pyi, logfire/_internal/config.py, logfire/_internal/config_params.py, tests/test_configure.py
Fixes https://github.com/pydantic/logfire/issues/441
Working on adding a test to fix coverage at the moment.
=> Support `'if-token-present'` for env var `'LOGFIRE_SEND_TO_LOGFIRE'`

logfire-api/logfire_api/_internal/auto_trace/rewrite_ast.pyi, logfire/_internal/auto_trace/rewrite_ast.py, tests/test_auto_trace.py
Closes https://github.com/pydantic/logfire/issues/495
Trying to compile a function in isolation caused an error when the function had `nonlocal`. So instead we just look for `yield` in the function definition AST.
=> Fix error in checking for generators in auto-tracing

CHANGELOG.md, logfire-api/logfire_api/_internal/config.pyi, logfire-api/logfire_api/_internal/integrations/aiohttp_client.pyi, logfire-api/logfire_api/_internal/integrations/asyncpg.pyi, logfire-api/logfire_api/_internal/integrations/celery.pyi, logfire-api/logfire_api/_internal/integrations/django.pyi, logfire-api/logfire_api/_internal/integrations/flask.pyi, logfire-api/logfire_api/_internal/integrations/httpx.pyi, logfire-api/logfire_api/_internal/integrations/mysql.pyi, logfire-api/logfire_api/_internal/integrations/psycopg.pyi, logfire-api/logfire_api/_internal/integrations/requests.pyi, logfire-api/pyproject.toml, pyproject.toml, uv.lock
=> Release v1.2.0

logfire/_internal/integrations/fastapi.py, logfire/_internal/main.py, tests/otel_integrations/test_fastapi.py
Multiple redundant changes to prevent errors in the patched `solve_dependencies` when a trace is excluded by sampling: 2 checks for `span.is_recording()` and wrapping in `handle_internal_errors`.
=> Handle NonRecordingSpans for fastapi arguments

logfire/_internal/ast_utils.py, tests/test_auto_trace.py
Closes https://github.com/pydantic/logfire/issues/440
=> Preserve docstrings in auto-tracing

logfire/integrations/logging.py, logfire/integrations/structlog.py, mkdocs.yml
We need to be careful about adding redirects for any changes of URL.
=> fix docs redirects

logfire/_internal/config.py
This way `logfire.code.work_dir` is set when the code source is configured via the `OTEL_RESOURCE_ATTRIBUTES` env var instead of `logfire.configure(code_source=...)`.
=> Set `logfire.code.work_dir` resource attribute whenever other code source attributes are present

docs/integrations/structlog.md
Small change, highlighted lines in https://logfire.pydantic.dev/docs/integrations/structlog/ are not consistent after a new line was added in b94bfc3
=> docs: Update hightlighted lines in structlog documentation

CHANGELOG.md, logfire-api/pyproject.toml, pyproject.toml, uv.lock
=> Release v2.1.2

.github/workflows/main.yml, Makefile, pyproject.toml, uv.lock
Also use the new [dev dependency groups in uv](https://docs.astral.sh/uv/concepts/dependencies/#development-dependencies).
@alexmojaki @Kludex I think you’re both off today, and I need to get CI passing, so I’m going to merge this to pin dependencies and thereby get tests passing.
As I said on slack, I think pinning deps in CI is the best route anyway, but happy to discuss other routes when your back, you can consider this a temporary fix until we discuss next week.
=> pin deps in CI

docs/plugins/main.py
Temporary fix for https://github.com/mkdocs/mkdocs-redirects/issues/65
=> Fix docs redirects SEO bug

.github/workflows/main.yml
Don't think we need the installs before `uv sync` with the explicit `--python` flag.
=> Simplify CI by removing unnecessary installs

pyproject.toml, tests/test_metrics.py, uv.lock
Following https://github.com/pydantic/logfire/pull/583#issuecomment-2473074709
It looks like by default exemplars shouldn't be created for measurements made outside of the context of a trace.
=> Fix tests for OTEL 1.28.1

logfire/_internal/ast_utils.py, tests/test_auto_trace.py
Closes https://github.com/pydantic/logfire/issues/595
=> Ignore trivial/empty functions in auto-tracing

logfire/_internal/json_encoder.py, logfire/_internal/json_schema.py, tests/test_json_args.py
Requested by @samuelcolvin.
I think it maybe makes sense to have a way for users to control this behavior more explicitly/independently of other use cases (e.g., via a magic `__pydantic_logfire_dump__` method?). But this seems reasonable to me for now. Not sure if we need to be concerned about it being a breaking change, or need to provide a way to opt into it or something.
- Closes https://github.com/pydantic/logfire/issues/521
=> Respect repr on fields when logging a dataclass

logfire/_internal/exporters/test.py, logfire/_internal/main.py, logfire/_internal/tracer.py, tests/test_logfire.py
I need to add tests, but I'll wait for @alexmojaki 's review.
I've implemented both `logfire.span(_links=...)` and `span.add_link`. I was planning to only implement `add_link` because it's easier to use, since you don't need to create a `Link`, but the `add_link` docstring from the OTel package actually recommends to use `_links`... So I've implemented both.
We can already see the links on Logfire itself:
=> Add span links

logfire/_internal/main.py, tests/test_logfire.py
=> Support `logfire.instrument` without arguments

logfire/_internal/auto_trace/import_hook.py, logfire/_internal/auto_trace/rewrite_ast.py, logfire/_internal/stack_info.py, tests/test_auto_trace.py, tests/test_source_code_extraction.py
1. When a file has invalid syntax, skip auto-tracing so that it can be imported normally and produce a normal traceback.
2. Handle internal errors when modifying and compiling the AST so that the app still works and just logs an error about auto-tracing failing.
For both of these, compiling had to be moved from the import loader to the import finder.
=> Handle errors in auto-tracing better

logfire/_internal/metrics.py, tests/test_metrics.py
Fixes error seen in https://github.com/pydantic/platform/actions/runs/11951891690/job/33317017710?pr=5933
These classes are private so we don't actually need good type hints here.
=> Allow new context argument of metric instrument methods to be passed positionally

.github/workflows/daily_deps_test.yml, .github/workflows/main.yml
And only test pydantic `main` in daily CI so that regular CI is stable.
=> Test pydantic 2.10 regularly

CHANGELOG.md, logfire-api/logfire_api/__init__.pyi, logfire-api/logfire_api/_internal/integrations/sqlite3.pyi, logfire-api/logfire_api/_internal/main.pyi, logfire-api/pyproject.toml, pyproject.toml, uv.lock
=> Release v2.6.0

logfire/_internal/json_formatter.py, pyproject.toml, uv.lock
Recent daily CI failures happen with pytest 8.3.4, so pinning it to 8.3.3 until https://github.com/15r10nk/inline-snapshot/issues/139 is fixed.
Upgrading other deps to confirm that latest deps work otherwise.
=> Pin pytest and upgrade deps to fix daily CI

logfire/integrations/structlog.py, tests/test_structlog.py
Closes https://github.com/pydantic/logfire/issues/636
Thanks @vikigenius for the report and suggested fix!
=> Use `exc_info` in structlog processor

logfire/_internal/formatter.py, pyproject.toml, tests/test_logfire.py, uv.lock
Since https://github.com/15r10nk/inline-snapshot/issues/139 is fixed
=> Remove pytest pin and update deps

logfire/_internal/utils.py
`os.fork()` copied the `SeededRandomIdGenerator` state so that the parent and child processes would generate the same pseudorandom trace/span IDs, which is very bad. Demo script that this PR fixes:
```python
import os
import logfire
logfire.info('log', pids=(os.fork(), os.getpid()))
```
=> Re-seed random ID generator after `os.fork()`

logfire/_internal/config.py
Something I've wanted to fix for a while, and recently I came across another forking bug which I fixed in https://github.com/pydantic/logfire/pull/644 so I decided to take care of this too
=> Update the `process.pid` resource attribute after `os.fork()`

docs/integrations/aws-lambda.md, logfire-api/logfire_api/__init__.py, logfire-api/logfire_api/__init__.pyi, logfire-api/logfire_api/_internal/integrations/aws_lambda.pyi, logfire-api/logfire_api/_internal/main.pyi, logfire/__init__.py, logfire/_internal/integrations/aws_lambda.py, logfire/_internal/main.py, mkdocs.yml, pyproject.toml, tests/otel_integrations/test_aws_lambda.py, tests/test_logfire_api.py, uv.lock
Suggestions on how to test this?
=> Add `logfire.instrument_aws_lambda`

logfire/_internal/json_encoder.py, logfire/_internal/json_schema.py, tests/test_json_args.py
Should fix bug seen in https://pydanticlogfire.slack.com/archives/C06EDRBSAH3/p1733920962935359
=> Fix erroneous `<circular reference>` when object is repeated in list

logfire/_internal/integrations/aiohttp_client.py, logfire/_internal/integrations/asyncpg.py, logfire/_internal/integrations/aws_lambda.py, logfire/_internal/integrations/celery.py, logfire/_internal/integrations/django.py, logfire/_internal/integrations/httpx.py, logfire/_internal/integrations/pymongo.py, logfire/_internal/integrations/redis.py, logfire/_internal/integrations/requests.py, logfire/_internal/integrations/sqlalchemy.py, logfire/_internal/integrations/sqlite3.py, logfire/_internal/integrations/starlette.py, logfire/_internal/integrations/system_metrics.py, tests/otel_integrations/test_asyncpg.py, tests/otel_integrations/test_celery.py, tests/otel_integrations/test_httpx.py, tests/otel_integrations/test_mysql.py, tests/otel_integrations/test_psycopg.py, tests/otel_integrations/test_redis.py, tests/otel_integrations/test_requests.py, tests/otel_integrations/test_sqlalchemy.py, tests/otel_integrations/test_sqlite3.py, tests/otel_integrations/test_system_metrics.py, tests/test_configure.py, uv.lock
Upgrade dependencies, particularly for the new OTEL release.
Fixes sqlalchemy tests by disabling the SQL commenter because it now adds the comments to `db.statement`: https://github.com/open-telemetry/opentelemetry-python-contrib/pull/2937
Also I was running into more warnings about checking tokens so I added some more `wait_for_check_token_thread` and related code, not related to the rest of the PR.
=> Upgrade to OTEL 1.29.0

docs/integrations/aiohttp.md
Add documentation demonstrating how to use AIOHTTP OpenTelemetry request hooks with a sample.
=> Document sample usage in docs for Opentelemetry AIOHTTP URL filter

docs/integrations/event-streams/faststream.md
I'm sorry to interrupt. Just wanted to make the example a little more consistent with our usage recommendations.
Thank you for adding such usage to the documentation!
=> docs: update FastStream example a bit

logfire/_internal/config.py, logfire/_internal/integrations/executors.py, tests/test_configure.py
1. Deserialize `advanced.id_generator`
2. Only call `configure` once per process, not once per submitted job
=> Fix patching of ProcessPoolExecutor

logfire/_internal/integrations/sqlalchemy.py, logfire/_internal/main.py, pyproject.toml, tests/otel_integrations/test_sqlalchemy.py, uv.lock
=> Support `AsyncEngine` to SQLAlchemy

logfire/_internal/integrations/httpx.py, logfire/_internal/main.py, tests/otel_integrations/test_httpx.py
Also added a new class `LogfireHttpxRequestInfo` that wraps the original OTEL `RequestInfo` and adds lots of tiny methods and properties breaking down the logic of capturing various things. The idea is that users could use this to easily build their own variations in hooks. Planning to do the same for responses.
=> `capture_request_text_body`

docs/integrations/llms/anthropic.md, logfire/__init__.py, logfire/_internal/integrations/llm_providers/anthropic.py, logfire/_internal/main.py, pyproject.toml, tests/otel_integrations/test_anthropic_bedrock.py, uv.lock
Added support for passing AnthropicBedrock and AsyncAnthropicBedrock clients to `instrument_anthropic()`
=> Support for AnthropicBedrock client

logfire/_internal/integrations/asyncpg.py, logfire/_internal/integrations/aws_lambda.py, logfire/_internal/main.py, tests/otel_integrations/test_aws_lambda.py
- Part of https://github.com/pydantic/logfire/issues/656
=> Remove hidden kwargs type from aws-lambda and asyncpg

logfire/_internal/json_encoder.py, logfire/_internal/json_schema.py, tests/test_pydantic_plugin.py
Closes https://github.com/pydantic/logfire/issues/728
=> Handle errors from `sqlalchemy.inspect`

logfire/_internal/cli.py, tests/test_cli.py
This is mainly a refactor on the test related to the `logfire inspect`, but I added the conditional to avoid showing the `opentelemetry-instrumentation-urllib3` when `requests` is installed.
=> Don't show `urllib3` when `requests` is installed on `logfire inspect`

logfire/_internal/json_schema.py
In V3, the instance attribute access will not work anymore.
=> Access `model_fields` on the model class

logfire/_internal/json_encoder.py
With this code:
```python
import vertexai
from vertexai.generative_models import GenerativeModel
import logfire
vertexai.init()
model = GenerativeModel('gemini-1.5-flash-002')
chat = model.start_chat()
response = chat.send_message('What is 2+2?')
logfire.info('response', response=response)
```
this PR changes the attributes from:
```json
{
"response": "candidates {\n  content {\n    role: \"model\"\n    parts {\n      text: \"2 + 2 = 4\\n\"\n    }\n  }\n  finish_reason: STOP\n  avg_logprobs: -5.3347812354331836e-06\n}\nusage_metadata {\n  prompt_token_count: 7\n  candidates_token_count: 8\n  total_token_count: 15\n}\nmodel_version: \"gemini-1.5-flash-002\"\n"
}
```
to
```json
{
"response": {
"candidates": [
{
"content": {
"role": "model",
"parts": [
{
"text": "2 + 2 = …
```
=> Try `to_dict` method when encoding JSON

logfire-api/logfire_api/__init__.py, logfire-api/logfire_api/__init__.pyi, logfire-api/logfire_api/_internal/main.pyi, logfire/__init__.py, logfire/_internal/main.py, tests/test_logfire.py, tests/test_logfire_api.py
I didn't see any obvious docs to update - any I should take a look at?
Closes #793
=> Add logfire.warning to mirror logging.warning

logfire/_internal/integrations/executors.py
Fixes problem reported in https://pydanticlogfire.slack.com/archives/C06EDRBSAH3/p1737061346996829
Before this PR, this:
```python
from concurrent.futures import ThreadPoolExecutor
from ddtrace.contrib.internal.futures.patch import patch
import logfire
patch()
ThreadPoolExecutor().submit(lambda: None).result()
```
raises:
```pytb
Traceback (most recent call last):
File "/Users/alex/Library/Application Support/JetBrains/PyCharm2024.3/scratches/scratch_990.py", line 11, in <module>
ThreadPoolExecutor().submit(lambda: None).result()
File "/Users/alex/.pyenv/versions/3.12.6/lib/python3.12/concurrent/futures/_base.py", line 449, in result
return self.__get_result()
^^^^^^^^^^^^^^^^^^^
File "/Users/alex/.pyenv/versions/3.12.6/lib/python3.12/concurrent/futures/_base.py", line …
```
=> Fix conflict with ddtrace futures patching by renaming fn parameter

logfire/_internal/exporters/console.py, tests/test_console_exporter.py
=> more resilient console logging

tests/test_configure.py
These tests were failing locally for me. FWIW:
```
>>> sys.version
'3.12.6 (main, Oct  6 2024, 20:30:11) [Clang 15.0.0 (clang-1500.3.9.4)]'
```
I didn't investigate why the regex doesn't work, this approach seems simpler and maybe better.
=> Test without `PROCESS_RUNTIME_DESCRIPTION_REGEX`

logfire-api/logfire_api/__init__.py, logfire-api/logfire_api/__init__.pyi, logfire-api/logfire_api/_internal/stack_info.pyi, logfire/__init__.py, logfire/_internal/stack_info.py, tests/test_logfire_api.py, tests/test_utils.py
Adds a public API for adding items to the tuple of non-user-code-prefixes, so that the frames are excluded in logfire spans. This will be used in `pydantic_ai`; see occurrences of the following in that codebase:
```python
try:
import logfire._internal.stack_info
except ImportError:
pass
else:
from pathlib import Path
logfire._internal.stack_info.NON_USER_CODE_PREFIXES += (str(Path(__file__).parent.absolute()),)
```
Closes #745
=> Add `logfire.add_non_user_code_prefix` function for library developers

.github/ISSUE_TEMPLATE/bug.yml, logfire-api/logfire_api/__init__.py, logfire-api/logfire_api/__init__.pyi, logfire-api/logfire_api/_internal/cli.pyi, logfire-api/logfire_api/_internal/config.pyi, logfire-api/logfire_api/_internal/exporters/otlp.pyi, logfire-api/logfire_api/_internal/utils.pyi, logfire/__init__.py, logfire/_internal/cli.py, tests/test_logfire_api.py
While creating #825 I realised there's no nice way to get the `logfire info` output if you don't have a terminal.
=> add `logfire.logfire_info()`

README.md, docs/index.md, docs/plugins/main.py, mkdocs.yml
- Lifts slack link near to the top of the sidebar and renames for visibility
- Removes `rye` from code snippets (SC suggestion)
- Adds slack badge to readme
Slight wording tweak
=> Make slack more prominent

logfire/_internal/json_encoder.py, tests/test_json_args.py
https://pydanticlogfire.slack.com/archives/C06EDRBSAH3/p1739205757483649
In general I think we need to start being more aggressive with catching exceptions here, we're working with arbitrary objects that may have all sorts of weirdness, and logging tracebacks about internal errors doesn't look good.
=> Catch more errors when checking for sqlalchemy objects

logfire/_internal/scrubbing.py, tests/test_secret_scrubbing.py
I've meant to do this for a while. The message being scrubbed has always been an annoying inconvenience, and other users probably feel the same. One day we should add an option to opt into scrubbing the message for extra security, but not today.
The reason that this change doesn't expose previously hidden potentially sensitive data is that the implementation was buggy from the beginning, since the unscrubbed message always remained in the status description (`otel_status_message`) anyway. That could be fixed, but I'd rather take this opportunity to not scrub by default.
=> Don't scrub exception message

logfire/_internal/config.py, logfire/_internal/logs.py, logfire/_internal/metrics.py, tests/conftest.py, tests/test_otel_logs.py
Some of the boilerplate we need to configure OTEL logs/events in logfire, similar to what we have for tracing and metrics. Does nothing by default and the configuration is tucked away in advanced options. Not comprehensive, e.g. doesn't have scrubbing.
=> Initial OTEL logs infra

logfire/_internal/config.py, tests/test_configure.py
Prevents `Exporter already shutdown, ignoring call` from being logged when `configure` is called twice.
=> Avoid double shutdown of logger provider

logfire/_internal/config.py, logfire/_internal/integrations/fastapi.py, logfire/_internal/integrations/httpx.py, logfire/_internal/integrations/psycopg.py, logfire/_internal/main.py, logfire/_internal/tracer.py, logfire/_internal/utils.py, tests/import_used_for_tests/internal_error_handling/internal_logfire_code_example.py, tests/test_utils.py, uv.lock
Fixes https://github.com/pydantic/logfire/issues/884 by making a context manager 'manually'. This should also be a bit faster, `contextlib._GeneratorContextManager` does a bunch of extra stuff internally.
=> Fix typing errors involving `handle_internal_errors`

docs/join-slack/index.html
Got this new link from slack support. Should be good for 2k uses (as opposed to 400 default). Expires in 1 year.
=> update slack link with 2k invite allowance

logfire/_internal/config.py, logfire/_internal/logs.py
This:
```python
import logfire
logfire.force_flush()
```
raised:
```pytb
Traceback (most recent call last):
File "/Users/alex/Library/Application Support/JetBrains/PyCharm2024.3/scratches/scratch_1108.py", line 3, in <module>
logfire.force_flush()
File "/Users/alex/work/logfire/logfire/_internal/main.py", line 830, in force_flush
return self._config.force_flush(timeout_millis)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/alex/work/logfire/logfire/_internal/config.py", line 1090, in force_flush
self._logger_provider.force_flush(timeout_millis)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/alex/work/logfire/logfire/_internal/logs.py", line 51, in __getattr__
result = getattr(self.provider, item)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoOpLoggerProvider' object has no …
```
=> Handle missing shutdown and force_flush on NoOpLoggerProvider better

logfire/_internal/json_encoder.py, tests/test_json_args.py
Prevents this:
```python
import unittest.mock
import logfire
logfire.info('hi', mock=unittest.mock.Mock())
```
from producing this:
and avoiding similar problems on other objects with `__getattr__`.
=> Handle mocks by calling `to_dict` on type

logfire/_internal/auto_trace/import_hook.py, tests/auto_trace_samples/__main__.py, tests/test_auto_trace.py
Closes https://github.com/pydantic/logfire/pull/904. Simply forwarding `get_code` wouldn't auto-trace because it would use the wrong code object.
=> Fix auto-tracing with `python -m`

logfire/_internal/cli.py, logfire/_internal/config.py, logfire/_internal/config_params.py, logfire/_internal/constants.py, tests/conftest.py, tests/test_cli.py, tests/test_configure.py
This goes hand in hand with a backend PR (private) that adds a region prefix to tokens.
=> Account for new EU region

.github/workflows/daily_deps_test.yml
Based on https://github.com/pydantic/logfire/actions/runs/14145453536:
1. Pydantic <= 2.7 doesn't support Python 3.13
2. `uv sync --python 3.8 --upgrade` insists on installing the latest from git despite what pyproject.toml says. Not worth debugging.
=> Fix python/pydantic versions tested in daily CI

tests/otel_integrations/test_openai_agents.py
Based on https://github.com/pydantic/logfire/actions/runs/14155852381
=> Require pydantic 2.7 for test_mcp

docs/how-to-guides/mcp-server.md
documentation error as the mcp argument for the read token has changed:
reference: https://github.com/pydantic/logfire-mcp?tab=readme-ov-file#configure-for-cursor
=> mcp-server.md: update token argument

logfire/_internal/config.py, logfire/_internal/constants.py, logfire/_internal/exporters/otlp.py, tests/exporters/test_otlp_session.py, tests/exporters/test_retry_fewer_spans.py
Replaces https://github.com/pydantic/logfire/pull/1026
- Measures the OTLP trace export body size before compression. This should prevent an edge case where the SDK could send a highly compressed payload of many spans that the backend would reject for being too big. Instead it will split the payload in two as usual.
- When a single span exceeds the SDK's 5MB limit, just send it.
- The backend has since increased its limit, so we shouldn't have been dropping it. This way the limits don't have to stay in sync.
- The SDK was supposed to be logging something in this case about the dropped span. But it was doing so with logfire, inside a context where instrumentation is suppressed. So the data was being dropped silently. Now, when the backend rejects a large payload that was otherwise not even …
=> Fix exporting of very large spans and payloads

logfire/_internal/stack_info.py
Fixes https://github.com/pydantic/logfire/issues/1028
=> Prevent infinite loop in get_user_frame_and_stacklevel

docs/integrations/web-frameworks/index.md
Closes https://github.com/pydantic/logfire/issues/1044
=> Update percentiles query to use WITHIN GROUP

logfire/_internal/config.py, tests/otel_integrations/test_django.py
Removed `http.server_name` and `http.host` attributes since for some users they are high cardinality. Since `http.server.active_requests` is an `UpDownCounter` and we use `AggregationTemporality.CUMULATIVE` for it, once an attribute combination is seen, it gets exported every minute even if the value is 0. This can result in a lot of data that most users don't know or care about.
=> Remove attributes from `http.server.active_requests` metric to prevent emitting too many

logfire/_internal/json_formatter.py, tests/test_console_exporter.py
Example script:
```python
import datetime
import decimal
import logfire
logfire.configure(console=logfire.ConsoleOptions(verbose=True))
logfire.info('hi', d=datetime.datetime.now(), v=decimal.Decimal('1.0'))
logfire.info('hi', x=None)
```
With this PR:
```
11:04:25.386 hi
│ scratch_1502.py:9 info
│ d=2025-05-14T13:04:25.366639
│ v=1.0
11:04:25.386 hi
│ scratch_1502.py:10 info
│ x=None
```
Before:
```
11:04:58.030 hi
│ scratch_1502.py:8 info
│ d=[
│       '2',
│       '0',
│       '2',
│       '5',
│       '-',
│       '0',
│       '5',
│       '-',
│       '1',
│       '4',
│       'T',
│       '1',
│       '3',
│       ':',
│       '0',
│       '4',
│       ':',
│       '5',
│       '8',
│       '.',
│       '0',
│       '1',
│       '0',
│       '7',
│       '1',
│       '4',
│   ]
│ …
```
=> More verbose console logging fixes

logfire/_internal/integrations/llm_providers/openai.py, tests/otel_integrations/test_openai.py
Quick fix that works in this case by setting the required semantic convention attributes:
```python
import openai
import logfire
client = openai.Client()
logfire.instrument_openai(client)  
response = client.chat.completions.create(
model='gpt-4',
messages=[
{'role': 'system', 'content': 'You are a helpful assistant.'},
{'role': 'user', 'content': 'Please write me a limerick about Python logging.'},
],
)
print(response.choices[0].message)
```
Might not cover all cases, haven't made sure. Also need to do the same for anthropic. And doesn't actually set the correct request model.
=> Make OpenAI spans show token usage in logfire UI

logfire/_internal/integrations/pydantic_ai.py, logfire/_internal/main.py
For situations like https://github.com/pydantic/pydantic-ai/pull/1739 which we don't currently support from here.
=> Add `**kwargs` to `instrument_pydantic_ai` for future compatibility

logfire/_internal/metrics.py, tests/test_metrics.py
Previously this script:
```python
import logfire
logfire.instrument_pydantic_ai()
logfire.instrument_pydantic_ai()
```
would log:
```
An instrument with name gen_ai.client.token.usage, type Histogram, unit {token} and description Measures number of input and output tokens used has been created already with a different advisory value None and will be used instead.
```
The reason was that `explicit_bucket_boundaries_advisory` was not being saved on the proxy histogram and used to recreate the real instrument when a new meter provider was set.
Also some refactoring.
=> Fix kwargs in proxy metric instruments, preventing warning about duplicate histograms

docs/integrations/web-frameworks/fastapi.md, logfire/_internal/integrations/fastapi.py, logfire/_internal/main.py
Changes the default of `extra_spans` (introduced in https://github.com/pydantic/logfire/pull/1258) in `logfire.instrument_fastapi` from True to False, and updates docs.
This is a breaking change that will trigger a major version release.
=> Remove extra FastAPI spans by default

logfire-api/logfire_api/__init__.py, tests/test_logfire_api.py
See https://github.com/pydantic/logfire/pull/1288#discussion_r2270880365
=> Ensure `logfire_api.LogfireSpan.context` and other attrs are None

logfire/_internal/integrations/sqlalchemy.py, tests/otel_integrations/test_sqlalchemy.py
Closes https://github.com/pydantic/logfire/issues/1334
=> Fix enable_commenter and commenter_options args of instrument_sqlalchemy

logfire-api/logfire_api/_internal/integrations/sqlalchemy.pyi, logfire-api/logfire_api/_internal/main.pyi, logfire/_internal/integrations/sqlalchemy.py, logfire/_internal/main.py, tests/otel_integrations/test_sqlalchemy.py
This PR addresses the need to properly instrument async `engines` values, as  mentioned in #1402's  review comment.
=> Support Instrumenting Async SqlAlchemy Engines
